agent_name: Structure_rag_zep
model: gpt-4o-mini
text_embedding: text-embedding-3-small
temperature: 0.7
input_length_limit: 10000000
buffer_length: 5000
output_dir: ./outputs/gpt-4o-mini-zep

agent_chunk_size: 4096   
service_name: azure_openai
retrieve_num: 10